# Generated by Django 5.2.13 on 2026-04-28 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boletas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SesionCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(unique=True)),
                ("monto_apertura", models.PositiveIntegerField(default=0)),
                ("hora_apertura", models.DateTimeField(auto_now_add=True)),
                ("hora_cierre", models.DateTimeField(blank=True, null=True)),
                ("monto_cierre", models.PositiveIntegerField(blank=True, null=True)),
                ("cerrada", models.BooleanField(default=False)),
                (
                    "usuario_apertura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aperturas_caja",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Caja",
                "verbose_name_plural": "Sesiones de Caja",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ingreso", "Ingreso"),
                            ("egreso", "Egreso"),
                            ("retiro", "Retiro"),
                        ],
                        max_length=10,
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("monto", models.PositiveIntegerField()),
                ("hora", models.DateTimeField(auto_now_add=True)),
                (
                    "boleta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boletas.boleta",
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="caja.sesioncaja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Caja",
                "verbose_name_plural": "Movimientos de Caja",
                "ordering": ["-hora"],
            },
        ),
    ]
