# Generated by Django 5.2.13 on 2026-04-28 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(unique=True)),
                ("fecha_emision", models.DateField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("emitida", "Emitida"),
                            ("pagada", "Pagada"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=10,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boletas",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boleta",
                "verbose_name_plural": "Boletas",
                "ordering": ["-fecha_emision", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="ItemBoleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("servicio", "Servicio"), ("repuesto", "Repuesto")],
                        default="servicio",
                        max_length=10,
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("cantidad", models.PositiveSmallIntegerField(default=1)),
                ("precio_unitario", models.PositiveIntegerField()),
                ("subtotal", models.PositiveIntegerField()),
                (
                    "boleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="boletas.boleta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Boleta",
                "verbose_name_plural": "Ítems de Boleta",
            },
        ),
    ]
